Repository kookmin-sw/capstone-2025-29, pull requests merged in 2025-05, with the labels that each got.

#69 Feat: 앱 푸시 알람 구현(SQS, Lambda)
  notification_server/lambda_function.py
Labels: 💻 backend, ✨ feat

#67 Feat: 카카오 OAuth2 로그인 기능 구현
  .github/workflows/deploy.yml
  backend/ongi_backend/build.gradle
  backend/ongi_backend/src/main/java/com/example/ongi_backend/Security/LoginFilter.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/Security/SecurityConfig.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/Security/oauth/KakaoUserInfo.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/Security/oauth/OAuth2SuccessHandler.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/Security/oauth/OAuth2UserService.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/Security/oauth/TemporaryUser.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/global/swagger/LoginDocController.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/user/Repository/BaseUserRepository.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/user/Service/UserService.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/user/entity/PrincipalDetails.java
  backend/ongi_backend/src/main/resources/application.yml
Labels: 💻 backend, ✨ feat

#95 Fix: API 연결 중 에러 처리
  .github/workflows/deploy.yml
  backend/ongi_backend/src/main/java/com/example/ongi_backend/global/entity/CurrentMatching.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/global/entity/VolunteerStatus.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/global/exception/ErrorCode.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/user/Service/ElderlyService.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/volunteerActivity/repository/VolunteerActivityRepository.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/volunteerActivity/service/VolunteerActivityService.java
Labels: 💻 backend, ✨ feat

#96 Feat/60 TTS 모델 로드, dockerfile 작성
  .DS_Store
  .github/workflows/deploy.yml
  .gitignore
  AI/.dockerignore
  AI/.gitignore
  AI/Dockerfile
  AI/main.py
  AI/model_test/STT(Whisper)/whisper.ipynb
  AI/model_test/STT_TTR.ipynb
  AI/model_test/TTR/TTR테스트.ipynb
  AI/modules/auth.py
  AI/modules/delete_audiofile.py
  AI/modules/emotion_module.py
  AI/modules/stt_module.py
  AI/modules/ttr_module.py
  AI/modules/tts_module.py
  AI/requirements.txt
Labels: 💻 ai

#100 Feat/99 : https 배포
  .github/workflows/deploy.yml
  AI/main.py
  AI/modules/tts_module.py
Labels: 💻 ai, ☁️ infra

#105 Feat/101
  .github/workflows/deploy.yml
  AI/main.py
  AI/modules/logger_module.py
  AI/modules/tts_module.py
  AI/requirements.txt
Labels: 💻 ai, ✨ feat

#109 Feat: 봉사자 추천 기능 구현
  .github/workflows/deploy.yml
  backend/ongi_backend/build.gradle
  backend/ongi_backend/src/main/java/com/example/ongi_backend/Security/SecurityConfig.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/global/config/RedisConfig.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/global/controller/Controller.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/global/exception/ErrorCode.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/global/grpc/GrpcUserClient.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/global/redis/listener/RedisKeyExpiredListener.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/global/redis/service/NotificationRedisService.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/global/redis/service/UnMatchingService.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/user/Controller/ElderlyController.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/user/Controller/UserController.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/user/Controller/VolunteerController.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/user/Dto/RecommendVolunteer.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/user/Dto/RequestMatching.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/user/Dto/RequestModify.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/user/Dto/RequestRecommendMatching.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/user/Dto/ResponseAvailableVolunteerDetail.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/user/Dto/ResponseRecommend.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/user/Dto/UserRegisterDto.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/user/Repository/VolunteerRepository.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/user/Service/ElderlyService.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/user/Service/UserService.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/user/Service/VolunteerService.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/user/entity/Volunteer.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/volunteerActivity/dto/RequestRecommend.java
  backend/ongi_backend/src/main/java/com/example/ongi_backend/volunteerActivity/service/VolunteerActivityService.java
  backend/ongi_backend/src/main/proto/user_recommendation.proto
  backend/ongi_backend/src/main/resources/application.yml
  recommend/Makefile
  recommend/db.py
  recommend/dockerfile
  recommend/grpc_server.py
  recommend/preprocessor.py
  recommend/recommender.py
  recommend/requirements.txt
  recommend/user_recommendation.proto
  recommend/volunteer_model.py
Labels: 💻 backend, ✨ feat, 🛠️ refactor

#121 Feat :감정 분석 자동화
  .github/workflows/deploy.yml
  AI/call_emotion.py
  AI/call_emotion.sh
  AI/main.py
  AI/modules/logger_module.py
  AI/modules/tts_module.py
Labels: 💻 ai, ✨ feat
